name: Code quality

on:
    push:
    pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./app  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .